### ISSUE TITLE
 arguments imply differing number of rows

### ISSUE THREAD

**Issue by adymimos** [jbkunst/d3wordcloud#18]
Unable to run the d3word cloud from the github install

```
> library("d3wordcloud")
> words <- c("I", "love", "this", "package", "but", "I", "don't", "like", "use", "wordclouds!", "voila")
> freqs <- rev(seq(length(words))) + 10
> 
> d3wordcloud(words, freqs)
Error in data.frame(text = as.character(words), freq = as.numeric(freqs),  : 
  arguments imply differing number of rows: 11, 0
```

**Comment by diegocgaona** [comment]
I'm having the same problem.

**Comment by jbkunst** [comment]
@diegocgaona  @adymimos 

Sorry about this. I need to test. Maybe this is cause of the @mrjoh3 recently PR. Not 100% sure. 

I'll take some time during this afternoon to see what is going on.

Regards!

**Comment by mrjoh3** [comment]
@jbkunst @diegocgaona @adymimos 

sorry this error is definitely from my original pull request. The more recent one has fixed the problem. 

The issue is that the original change inadvertently made the 'label' parameter a required field (not the intention). It should now be completely optional once the latest pull request is accepted.

apologies

**Comment by diegocgaona** [comment]
@jbkunst @mrjoh3, now is working fine!!! 

Thanks for this useful package!
:)

**Comment by jbkunst** [comment]
Thanks @mrjoh3
