### ISSUE TITLE
is it possible to change word colors?

### ISSUE THREAD

**Issue by jpmarindiaz** [jbkunst/d3wordcloud#6]
I'd like to use some other color palette in the wordcloud, is it possible?

**Comment by jbkunst** [comment]
Hi,

 It is no possible by now. Give me a couple of days for code this new functionality ;)

Regards,

**Comment by jpmarindiaz** [comment]
That would be awesome!
It would great to select one from a set of predefined palettes of even give echar word its own color.
Thanks so much

**Comment by jbkunst** [comment]
Ok! Now it is possible add colors ;). Please check the demo in http://rpubs.com/jbkunst/100416

The argument is `colors`, if you give a hexdecimal color vector with `length(colors) == length(words)` every word will have its own color (order by index), otherwise a gradient is created.

Hope it helps.

Thanks for the recommendation.

Regards,
